// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function ClearPayloads():Promise<void>;

export function ConnectSSH(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DisconnectSSH():Promise<void>;

export function ExportJSON(arg1:string):Promise<void>;

export function GetPayloads():Promise<Array<store.Payload>>;

export function GetPort():Promise<number>;

export function GetSSHState():Promise<main.SSHState>;

export function Restart():Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function Show():Promise<void>;
