// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPayloads() {
  return window['go']['main']['App']['ClearPayloads']();
}

export function ConnectSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2, arg3);
}

export function DisconnectSSH() {
  return window['go']['main']['App']['DisconnectSSH']();
}

export function ExportJSON(arg1) {
  return window['go']['main']['App']['ExportJSON'](arg1);
}

export function GetPayloads() {
  return window['go']['main']['App']['GetPayloads']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function GetSSHState() {
  return window['go']['main']['App']['GetSSHState']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}
